const { verifyQuote } = require('./sgx-quote-verify.js');

const API_KEY = '';

const CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIInTTCCJtKgAwIBAgIBATAKBggqhkjOPQQDAjA5MQ4wDAYDVQQDDAVSQVRMUzEa
MBgGA1UECgwRR3JhbWluZURldmVsb3BlcnMxCzAJBgNVBAYTAlVTMB4XDTAxMDEw
MTAwMDAwMFoXDTMwMTIzMTIzNTk1OVowOTEOMAwGA1UEAwwFUkFUTFMxGjAYBgNV
BAoMEUdyYW1pbmVEZXZlbG9wZXJzMQswCQYDVQQGEwJVUzB2MBAGByqGSM49AgEG
BSuBBAAiA2IABLIJM7b+QEfhSzi+W3xyTXJjWgOY74ffZK1/hAAN+SEWw4LM4r2N
CaO7d+d+SYfz4xD9xZNIE9n5Ye9gtza5cOzhdXJfvq4PWIUrYqNdZgMv9wP4WbEd
BuMe4bl0wAfNy6OCJawwgiWoMAkGA1UdEwQCMAAwHQYDVR0OBBYEFEZ1m3KKMjrb
JtcX8TLkbTH9DgshMB8GA1UdIwQYMBaAFEZ1m3KKMjrbJtcX8TLkbTH9DgshMIIS
jwYLBgkqhkiG+E2KOQYEghJ+AwACAAAAAAALABAAk5pyM/ecTKmUCg2zlX8GBzHY
ZnPjRzAOKJvKSOrkw1wAAAAACwsQD///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAADnAAAAAAAAAEuP0hn3oauwrGok3CL+
XiGRjiWCnas+lkBMFxcmckGyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AADVBFQ7w3F+2H05gvu3sX87B/Erpmtp91wCU2Yg810NWwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AABQ07NtIpwmbMxgKVDqS9If/YOf7SuKTL8gsYVOtaHrygAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAyhAAACmQ6P/SRx17MF9Z2DOZsbdPKO2gBFq0MZef
6WwNIkqN9O0ZLHD4r939MN/vd4ag4k9t3HzW8vJY6sz3qta3TumJj/gYqDrGfn61
EyElu/Mq1tZuH2WlnYIdvSD+XqmRzC6oOOcBq/47gsJ3Hb9ST0uU3FG1mMBw2RIg
4QnitXwOCwsQD///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAFQAAAAAAAADnAAAAAAAAAHj+jP0BCVoPEIr/XEBiS5NhLWwotz4ajSgX
nJ3fDgaGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMT1d115ZQPpYT
f3fGioKaAFasje1wFAsIGwlEkMV7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgvjSEDK2t+Mr
8VLFHtrgoZ9Fx1yn6L6bX9W+5aJZvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAB5bE2MeP5Cx0Lx3Qf2Pxgisju8TTwKLd+46cjn6cRFPOTMK5Nnla6YQL
p4WWWfJMVeeS5Mctx+0xKlh4I9+IHyAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYX
GBkaGxwdHh8FAGIOAAAtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRThq
Q0NCSmlnQXdJQkFnSVVNc1RGd3dOZjZkVXRBeEcwZ0l2L2tzS2tVK0l3Q2dZSUtv
Wkl6ajBFQXdJdwpjREVpTUNBR0ExVUVBd3daU1c1MFpXd2dVMGRZSUZCRFN5QlFi
R0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSClNXNTBaV3dnUTI5eWNHOXlZWFJw
YjI0eEZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUkKREFK
RFFURUxNQWtHQTFVRUJoTUNWVk13SGhjTk1qVXhNVEE0TURJeU5qUXpXaGNOTXpJ
eE1UQTRNREl5TmpRegpXakJ3TVNJd0lBWURWUVFEREJsSmJuUmxiQ0JUUjFnZ1VF
TkxJRU5sY25ScFptbGpZWFJsTVJvd0dBWURWUVFLCkRCRkpiblJsYkNCRGIzSndi
M0poZEdsdmJqRVVNQklHQTFVRUJ3d0xVMkZ1ZEdFZ1EyeGhjbUV4Q3pBSkJnTlYK
QkFnTUFrTkJNUXN3Q1FZRFZRUUdFd0pWVXpCWk1CTUdCeXFHU000OUFnRUdDQ3FH
U000OUF3RUhBMElBQlBiMwphZDU4NmI0ZCtQR0duL2NQRnUxREg2L21QYnhDTXIw
T1pzNmliWVRNZWJVQUc2SGJaNnBVZXljRk83TlFsMGljCjJNeWFjUEZCUU5NY09n
UHNYUkdqZ2dNT01JSURDakFmQmdOVkhTTUVHREFXZ0JTVmIxM052UnZoNlVCSnlk
VDAKTTg0QlZ3dmVWREJyQmdOVkhSOEVaREJpTUdDZ1hxQmNobHBvZEhSd2N6b3ZM
MkZ3YVM1MGNuVnpkR1ZrYzJWeQpkbWxqWlhNdWFXNTBaV3d1WTI5dEwzTm5lQzlq
WlhKMGFXWnBZMkYwYVc5dUwzWTBMM0JqYTJOeWJEOWpZVDF3CmJHRjBabTl5YlNa
bGJtTnZaR2x1Wnoxa1pYSXdIUVlEVlIwT0JCWUVGUEhqQ2JPSStJTG5ybWlLdTlv
eHJXTmgKWnByR01BNEdBMVVkRHdFQi93UUVBd0lHd0RBTUJnTlZIUk1CQWY4RUFq
QUFNSUlDT3dZSktvWklodmhOQVEwQgpCSUlDTERDQ0FpZ3dIZ1lLS29aSWh2aE5B
UTBCQVFRUWRmbklCSURkOHhITG1RU1FFWFNoV3pDQ0FXVUdDaXFHClNJYjRUUUVO
QVFJd2dnRlZNQkFHQ3lxR1NJYjRUUUVOQVFJQkFnRUxNQkFHQ3lxR1NJYjRUUUVO
QVFJQ0FnRUwKTUJBR0N5cUdTSWI0VFFFTkFRSURBZ0VETUJBR0N5cUdTSWI0VFFF
TkFRSUVBZ0VETUJFR0N5cUdTSWI0VFFFTgpBUUlGQWdJQS96QVJCZ3NxaGtpRytF
MEJEUUVDQmdJQ0FQOHdFQVlMS29aSWh2aE5BUTBCQWdjQ0FRQXdFQVlMCktvWklo
dmhOQVEwQkFnZ0NBUUF3RUFZTEtvWklodmhOQVEwQkFna0NBUUF3RUFZTEtvWklo
dmhOQVEwQkFnb0MKQVFBd0VBWUxLb1pJaHZoTkFRMEJBZ3NDQVFBd0VBWUxLb1pJ
aHZoTkFRMEJBZ3dDQVFBd0VBWUxLb1pJaHZoTgpBUTBCQWcwQ0FRQXdFQVlMS29a
SWh2aE5BUTBCQWc0Q0FRQXdFQVlMS29aSWh2aE5BUTBCQWc4Q0FRQXdFQVlMCktv
WklodmhOQVEwQkFoQUNBUUF3RUFZTEtvWklodmhOQVEwQkFoRUNBUTB3SHdZTEtv
WklodmhOQVEwQkFoSUUKRUFzTEF3UC8vd0FBQUFBQUFBQUFBQUF3RUFZS0tvWklo
dmhOQVEwQkF3UUNBQUF3RkFZS0tvWklodmhOQVEwQgpCQVFHQUdCcUFBQUFNQThH
Q2lxR1NJYjRUUUVOQVFVS0FRRXdIZ1lLS29aSWh2aE5BUTBCQmdRUUJEdkhGM3J2
CkYrdEZqNXA1WHEyWDNEQkVCZ29xaGtpRytFMEJEUUVITURZd0VBWUxLb1pJaHZo
TkFRMEJCd0VCQWY4d0VBWUwKS29aSWh2aE5BUTBCQndJQkFmOHdFQVlMS29aSWh2
aE5BUTBCQndNQkFmOHdDZ1lJS29aSXpqMEVBd0lEU0FBdwpSUUloQU9ScU0va1Fr
S0g4MTRuSW53SXBPUTRYN2tFdDgzKzU3SnhxSThkc1B4ZWZBaUJJY1RzdXU1c1Uv
ak1HCmNadklvRGkzZlV5ZEkweTVtTk03UGVzRFNpd1BQUT09Ci0tLS0tRU5EIENF
UlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNs
akNDQWoyZ0F3SUJBZ0lWQUpWdlhjMjlHK0hwUUVuSjFQUXp6Z0ZYQzk1VU1Bb0dD
Q3FHU000OUJBTUMKTUdneEdqQVlCZ05WQkFNTUVVbHVkR1ZzSUZOSFdDQlNiMjkw
SUVOQk1Sb3dHQVlEVlFRS0RCRkpiblJsYkNCRApiM0p3YjNKaGRHbHZiakVVTUJJ
R0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUXN3Q1FZ
RFZRUUdFd0pWVXpBZUZ3MHhPREExTWpFeE1EVXdNVEJhRncwek16QTFNVEV4TURV
d01UQmFNSEF4SWpBZwpCZ05WQkFNTUdVbHVkR1ZzSUZOSFdDQlFRMHNnVUd4aGRH
WnZjbTBnUTBFeEdqQVlCZ05WQkFvTUVVbHVkR1ZzCklFTnZjbkJ2Y21GMGFXOXVN
UlF3RWdZRFZRUUhEQXRUWVc1MFlTQkRiR0Z5WVRFTE1Ba0dBMVVFQ0F3Q1EwRXgK
Q3pBSkJnTlZCQVlUQWxWVE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNE
UWdBRU5TQi83dDIxbFhTTwoyQ3V6cHh3NzRlSkI3MkV5REdnVzVyWEN0eDJ0VlRM
cTZoS2s2eitVaVJaQ25xUjdwc092Z3FGZVN4bG1UbEpsCmVUbWkyV1l6M3FPQnV6
Q0J1REFmQmdOVkhTTUVHREFXZ0JRaVpReldXcDAwaWZPRHRKVlN2MUFiT1NjR3JE
QlMKQmdOVkhSOEVTekJKTUVlZ1JhQkRoa0ZvZEhSd2N6b3ZMMk5sY25ScFptbGpZ
WFJsY3k1MGNuVnpkR1ZrYzJWeQpkbWxqWlhNdWFXNTBaV3d1WTI5dEwwbHVkR1Zz
VTBkWVVtOXZkRU5CTG1SbGNqQWRCZ05WSFE0RUZnUVVsVzlkCnpiMGI0ZWxBU2Nu
VTlEUE9BVmNMM2xRd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dR
SU1BWUIKQWY4Q0FRQXdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdYc1ZraTB3K2k2
VllHVzNVRi8yMnVhWGUwWUpEajFVZQpuQStUakQxYWk1Y0NJQ1liMVNBbUQ1eGtm
VFZwdm80VW95aVNZeHJEV0xtVVI0Q0k5Tkt5ZlBOKwotLS0tLUVORCBDRVJUSUZJ
Q0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDanpDQ0Fq
U2dBd0lCQWdJVUltVU0xbHFkTkluemc3U1ZVcjlRR3prbkJxd3dDZ1lJS29aSXpq
MEVBd0l3CmFERWFNQmdHQTFVRUF3d1JTVzUwWld3Z1UwZFlJRkp2YjNRZ1EwRXhH
akFZQmdOVkJBb01FVWx1ZEdWc0lFTnYKY25CdmNtRjBhVzl1TVJRd0VnWURWUVFI
REF0VFlXNTBZU0JEYkdGeVlURUxNQWtHQTFVRUNBd0NRMEV4Q3pBSgpCZ05WQkFZ
VEFsVlRNQjRYRFRFNE1EVXlNVEV3TkRVeE1Gb1hEVFE1TVRJek1USXpOVGsxT1Zv
d2FERWFNQmdHCkExVUVBd3dSU1c1MFpXd2dVMGRZSUZKdmIzUWdRMEV4R2pBWUJn
TlZCQW9NRVVsdWRHVnNJRU52Y25CdmNtRjAKYVc5dU1SUXdFZ1lEVlFRSERBdFRZ
VzUwWVNCRGJHRnlZVEVMTUFrR0ExVUVDQXdDUTBFeEN6QUpCZ05WQkFZVApBbFZU
TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFQzZuRXdNRElZWk9q
L2lQV3NDemFFS2k3CjFPaU9TTFJGaFdHamJuQlZKZlZua1k0dTNJamtEWVlMME14
TzRtcXN5WWpsQmFsVFZZeEZQMnNKQks1emxLT0IKdXpDQnVEQWZCZ05WSFNNRUdE
QVdnQlFpWlF6V1dwMDBpZk9EdEpWU3YxQWJPU2NHckRCU0JnTlZIUjhFU3pCSgpN
RWVnUmFCRGhrRm9kSFJ3Y3pvdkwyTmxjblJwWm1sallYUmxjeTUwY25WemRHVmtj
MlZ5ZG1salpYTXVhVzUwClpXd3VZMjl0TDBsdWRHVnNVMGRZVW05dmRFTkJMbVJs
Y2pBZEJnTlZIUTRFRmdRVUltVU0xbHFkTkluemc3U1YKVXI5UUd6a25CcXd3RGdZ
RFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUV3Q2dZ
SQpLb1pJemowRUF3SURTUUF3UmdJaEFPVy81UWtSK1M5Q2lTRGNOb293THVQUKXN
XR2YvWWk3R1NWOTRCZ3dUd2cKQWlFQTRKMGxySG9NcytYbzVvL3NYNk85UVd4SFJB
dlpVR09kUlE3Y3ZxUlhhcUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KAFgz
oWtwdWJrZXktaGFzaFgkggFYIFDTs20inCZszGApUOpL0h/9g5/tK4pMvyCxhU61
oevKMAoGCCqGSM49BAMCA2kAMGYCMQD9BiB1e/3XVxvglyvr2kYS6wMYCXUbTEEW
idsnuhutZrrNzqtByVOy8GJdqs4jJLoCMQDyLU8aMen+G/B5YkSHjg7wA/n3VgVB
DBYRST7v1S+IO8HqcU8HZFNbC+J5y1U7Lhk=
-----END CERTIFICATE-----`;

const cache = new Map();

async function cacheRead(key) {
    const value = cache.get(key);
    if (value) {
        console.log(`[CACHE] Hit: ${key}`);
    }
    return value || null;
}

async function cacheWrite(key, data) {
    console.log(`[CACHE] Write: ${key}`);
    cache.set(key, data);
}

async function runTest() {
    console.log('='.repeat(80));
    console.log('SGX Quote Verification Test');
    console.log('='.repeat(80));
    console.log();
    
    console.log('[PHASE 1] Starting quote verification...');
    console.log();
    
    const options = {
        apiKey: API_KEY,
        pccsUrl: 'https://api.trustedservices.intel.com/sgx/certification/v4',
        cacheRead,
        cacheWrite,
        allowDebugEnclave: true,
        allowOutdatedTcb: true,
        allowHwConfigNeeded: true,
        allowSwHardeningNeeded: true
    };
    
    try {
        const result = await verifyQuote(CERTIFICATE, options);
        
        console.log();
        console.log('='.repeat(80));
        console.log('VERIFICATION RESULT');
        console.log('='.repeat(80));
        console.log();
        
        if (result.verified) {
            console.log('✓ Quote verification PASSED');
            console.log();
            console.log('Verification Result:', result.verificationResult);
            console.log('TCB Status:', result.tcbStatus);
            console.log('Quote Version:', result.quoteVersion);
            console.log('Attestation Key Type:', result.attestationKeyType);
            console.log();
            console.log('Measurements:');
            console.log('  MRENCLAVE:', result.measurements.mrenclave);
            console.log('  MRSIGNER:', result.measurements.mrsigner);
            console.log('  ISV_PROD_ID:', result.measurements.isvProdId);
            console.log('  ISV_SVN:', result.measurements.isvSvn);
            console.log('  Attributes:', result.measurements.attributes);
            console.log('  Report Data:', result.measurements.reportData);
        } else {
            console.log('✗ Quote verification FAILED');
            console.log();
            console.log('Error:', result.error);
            if (result.stack) {
                console.log();
                console.log('Stack trace:');
                console.log(result.stack);
            }
        }
        
        console.log();
        console.log('='.repeat(80));
        
    } catch (error) {
        console.error();
        console.error('='.repeat(80));
        console.error('UNEXPECTED ERROR');
        console.error('='.repeat(80));
        console.error();
        console.error('Error:', error.message);
        console.error();
        console.error('Stack trace:');
        console.error(error.stack);
        console.error();
        console.error('='.repeat(80));
        process.exit(1);
    }
}

runTest().then(() => {
    console.log();
    console.log('Test completed successfully');
    process.exit(0);
}).catch(error => {
    console.error();
    console.error('Test failed with unexpected error:', error);
    process.exit(1);
});
